@startuml ICpuIdFactory

abstract class ICpuIdFactory {
    +{abstract} create(cpunum: int) : unique_ptr<ICpuId>
    +~ICpuIdFactory() = default
}

class " " as Global <<(G,#FF7700) global free>> {
    +CreateCpuIdFactory(config: const Config&) :\n    std::unique_ptr<ICpuIdFactory>
}

class CpuIdFactoryWithCallback<CreationCallback> {
    +CpuIdFactoryWithCallback(callback: CreationCallback&)
    +create(cpunum: int) : unique_ptr<ICpuId>
}
note bottom
    The `create` method then uses
    the callback to instantiate the
    `ICpuId` object.
end note

ICpuIdFactory <|.d. CpuIdFactoryWithCallback

Global::CreateCpuIdFactory -r-> CpuIdFactoryWithCallback::CpuIdFactoryWithCallback

@enduml
